### PR TITLE
add known hosts verification

### PR DESCRIPTION
**Pull request by drewaogle**
- Adds `VerifyType` to control how verification is done.
- sets `VerifyType.KNOWN_HOSTS` as the default action
- sets "*.aperturedata.io" as the known hosts.
- adds accessors for manipulating the known host list.
- adds `ADB_SSL_CA_FILE` as an environment variable usable for passing in a pem file for verification.

### CODE REVIEW

**Comment by drewaogle** [comment]
I've verified this works
- verifying connection to the cloud
- not verifying a connection to localhost
- failing to verify a self signed cert to localhost when localhost is added to know hosts.
- failing to verify a ca signed cert for localhost when the ca is missing from the ca store
- verifying with the ca signed cert for localhost after the ca is added.
- verifying with the ca signed cert for localhost with the ca cert passed in with ADB_SSL_CA_FILE

**Comment by drewaogle** [comment]
If we add verification, I think we want to be able to know that we fail bad certs, as well as pass the expected cases, so if we do anything that were to change the operations, we would catch it.

I added the ADB_SSL_CA_FILE for hooking that up in tests, but adding those will be a lot of work.

**Comment by ali-asadpoor** [comment]
@drewaogle Not sure if I understand the code, is this prevents client to accept self signed certs by default?

**Comment by drewaogle** [comment]
> @drewaogle Not sure if I understand the code, is this prevents client to accept self signed certs by default?

By default it chooses enforcement by what host you are connecting to. If you are connecting to a *.aperturedata.io host, it will require a non-self-signed certificate.

**Comment by drewaogle** [comment]
not usable

**Pull request closed without merging**
