### PR TITLE
Remove dbinfo from all examples.

### PR DESCRIPTION
**Pull request by gsaluja9**
Also corrected a NB based on a user trial.

### CODE REVIEW

**Review by bovlb — DISMISSED** [review]
LGTM.  Two questions:
* Why change the search set in examples/similarity_search/similarity_search.ipynb ?
* Why not delete examples/loaders_101/dbinfo.py ?

Note dbinfo is still used in tests.

**Review by luisremis — APPROVED** [review]
thanks!

**Comment by gsaluja9** [comment]
> LGTM. Two questions:
> 
> * Why change the search set in examples/similarity_search/similarity_search.ipynb ?
> * Why not delete examples/loaders_101/dbinfo.py ?
> 
> Note dbinfo is still used in tests.
similarity_search.ipynb introduces another alternate way to run the example via adb cli, which does not take arbitrary descriptorset names, but applies the model name used to generate the embeddings. Changing the name keeps the example working with either ways of ingesting.

I shall remove  dbinfo from loaders_101.
Not given a thought  as to how to remove it from tests.

**Review by drewaogle — APPROVED** [review]
love it!

**Pull request merged**
