### PR TITLE
Remove unused `get_uniqueids` and `get_images_uniqueids`

### PR DESCRIPTION
**Pull request by luisremis**
Newer versions of [aperturedb API will prevent the use of internal class names](https://github.com/aperture-data/athena/pull/1490) (i.e., `_Image`, `_Descriptor`, etc) on `FindEntity` commands. `get_uniqueids` and `get_images_uniqueids` rely on that to work correctly.

Currently, there seem to be no applications using `get_uniqueids` and `get_images_uniqueids`, nor internal tests cases or classes that use any them.

### CODE REVIEW

**Comment by gsaluja9** [comment]
- [ ] The docs build would need to be re triggered.
- [ ] This is being used in one of the customer app repo. Would need a removal.

Other than that, changes are good to go.

**Review by gsaluja9 — APPROVED** [review]
lgtm

**Comment by gsaluja9** [comment]
This also affects various calls to count_entities in utils to @luisremis , @drewaogle

**Comment by drewaogle** [comment]
Sounds good. I don't use any of these directly, iirc.

**Pull request merged**
