### PR TITLE
Minimal Python Package

### PR DESCRIPTION
**Pull request by drewaogle**

### CODE REVIEW

**Comment by bovlb** [comment]
Did we consider using `extras_require` instead?

**Comment by drewaogle** [comment]
> Did we consider using `extras_require` instead?

yes. The problem is that it would then break every place we currently use the module.

**Comment by bovlb** [comment]
> > Did we consider using `extras_require` instead?
> 
> yes. The problem is that it would then break every place we currently use the module.

Painful I agree, but the result would be cleaner in the long run, especially if we think of other variations (e.g. labelling libraries).  We could deploy it in three steps:
1. Add empty extras for "notebook" or whatever.
2. Switch everywhere that needs to to use the extra.
3. Move non-minimal dependencies into the extras.

**Comment by drewaogle** [comment]
> > > Did we consider using `extras_require` instead?
> > 
> > 
> > yes. The problem is that it would then break every place we currently use the module.
> 
> Painful I agree, but the result would be cleaner in the long run, especially if we think of other variations (e.g. labelling libraries). We could deploy it in three steps:
> 
> 1. Add empty extras for "notebook" or whatever.
> 2. Switch everywhere that needs to to use the extra.
> 3. Move non-minimal dependencies into the extras.

We can always pull that trigger at any point. I think what we can do for now is work on splitting the items into the logical components. A good number of things have a monolithic package and a "pick your own" anyway.

**Comment by gsaluja9** [comment]
As per our discussion the other day, and with our definition of core, complete and dev versions, this [PR](https://github.com/aperture-data/aperturedb-python/pull/312) tries to accomplish these goals in the commonly advocated way.

@drewaogle , I think the overhead of installing pandas and such stuff is minimal, so we should aim to close this. If not, it'd be better to make changes to pyproject.toml.

**Comment by drewaogle** [comment]
> As per our discussion the other day, and with our definition of core, complete and dev versions, this [PR](https://github.com/aperture-data/aperturedb-python/pull/312) tries to accomplish these goals in the commonly advocated way.
> 
> @drewaogle , I think the overhead of installing pandas and such stuff is minimal, so we should aim to close this. If not, it'd be better to make changes to pyproject.toml.

I still think this is useful.

An `aperturedb` package is good for data scientists
An `aperturedb-minimal` package is good for system integrators that want to expose themselves to minimal dependencies.

We don't need to move on this one right now.

**Comment by luisremis** [comment]
I think this is stale and can be closed. please re-open it otherwise.

**Pull request closed without merging**
